name: Self-hosted runner (push)

on:
  push:
    branches:
      - master
      - ci_*
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
  repository_dispatch:

jobs:
  run_tests_mindspore_gpu:
    runs-on: [self-hosted, docker-gpu, single-gpu]
    container:
      image: mindspore/mindspore:1.8.0-cuda11.1-cudnn8-runtime
      options: --gpus 0 --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      - name: NVIDIA-SMI
        run: |
          nvidia-smi

      - name: Install dependencies
        run: |
          apt -y update && apt install -y libsndfile1-dev
          pip install --upgrade pip
          pip install .[sklearn,testing,onnxruntime,sentencepiece,speech]

      - name: Are GPUs recognized by our DL frameworks
        run: |
          python -c "import mindspore; print('Cuda available:', mindspore.cuda.is_available())"
          python -c "import mindspore; print('Cuda version:', mindspore.version.cuda)"
          python -c "import mindspore; print('CuDNN version:', mindspore.backends.cudnn.version())"
          python -c "import mindspore; print('Number of GPUs available:', mindspore.cuda.device_count())"

      - name: Run all non-slow tests on GPU
        env:
          OMP_NUM_THREADS: 8
          MKL_NUM_THREADS: 8
          HF_HOME: /mnt/cache
        run: |
          python -m pytest -n 2 --dist=loadfile --make-reports=tests_mindspore_gpu tests

      - name: Failure short reports
        if: ${{ always() }}
        run: cat reports/tests_mindspore_gpu_failures_short.txt

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_all_tests_mindspore_gpu_test_reports
          path: reports

  run_tests_tf_gpu:
    runs-on: [self-hosted, docker-gpu, single-gpu]
    container:
      image: tensorflow/tensorflow:2.4.1-gpu
      options: --gpus 0 --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      - name: NVIDIA-SMI
        run: |
          nvidia-smi

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[sklearn,testing,onnxruntime,sentencepiece]

      - name: Are GPUs recognized by our DL frameworks
        run: |
          TF_CPP_MIN_LOG_LEVEL=3 python -c "import tensorflow as tf; print('TF GPUs available:', bool(tf.config.list_physical_devices('GPU')))"
          TF_CPP_MIN_LOG_LEVEL=3 python -c "import tensorflow as tf; print('Number of TF GPUs available:', len(tf.config.list_physical_devices('GPU')))"

      - name: Run all non-slow tests on GPU
        env:
          OMP_NUM_THREADS: 8
          MKL_NUM_THREADS: 8
          TF_NUM_INTRAOP_THREADS: 8
          TF_NUM_INTEROP_THREADS: 1
          HF_HOME: /mnt/cache
        run: |
          python -m pytest -n 2 --dist=loadfile --make-reports=tests_tf_gpu tests

      - name: Failure short reports
        if: ${{ always() }}
        run: cat reports/tests_tf_gpu_failures_short.txt

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_all_tests_tf_gpu_test_reports
          path: reports


  run_tests_mindspore_multi_gpu:
    runs-on: [self-hosted, docker-gpu, multi-gpu]
    container:
      image: mindspore/mindspore:1.8.0-cuda11.1-cudnn8-runtime
      options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      - name: NVIDIA-SMI
        run: |
          nvidia-smi

      - name: Install dependencies
        run: |
          apt -y update && apt install -y libsndfile1-dev
          pip install --upgrade pip
          pip install .[sklearn,testing,onnxruntime,sentencepiece,speech]

      - name: Are GPUs recognized by our DL frameworks
        run: |
          python -c "import mindspore; print('Cuda available:', mindspore.cuda.is_available())"
          python -c "import mindspore; print('Cuda version:', mindspore.version.cuda)"
          python -c "import mindspore; print('CuDNN version:', mindspore.backends.cudnn.version())"
          python -c "import mindspore; print('Number of GPUs available:', mindspore.cuda.device_count())"

      - name: Run all non-slow tests on GPU
        env:
          OMP_NUM_THREADS: 8
          MKL_NUM_THREADS: 8
          MKL_SERVICE_FORCE_INTEL: 1
          HF_HOME: /mnt/cache
        run: |
          python -m pytest -n 2 --dist=loadfile --make-reports=tests_mindspore_multi_gpu tests

      - name: Failure short reports
        if: ${{ always() }}
        run: cat reports/tests_mindspore_multi_gpu_failures_short.txt

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_all_tests_mindspore_multi_gpu_test_reports
          path: reports

  run_tests_tf_multi_gpu:
    runs-on: [self-hosted, docker-gpu, multi-gpu]
    container:
      image: tensorflow/tensorflow:2.4.1-gpu
      options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      - name: NVIDIA-SMI
        run: |
          nvidia-smi

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[sklearn,testing,onnxruntime,sentencepiece]

      - name: Are GPUs recognized by our DL frameworks
        run: |
          TF_CPP_MIN_LOG_LEVEL=3 python -c "import tensorflow as tf; print('TF GPUs available:', bool(tf.config.list_physical_devices('GPU')))"
          TF_CPP_MIN_LOG_LEVEL=3 python -c "import tensorflow as tf; print('Number of TF GPUs available:', len(tf.config.list_physical_devices('GPU')))"

      - name: Run all non-slow tests on GPU
        env:
          OMP_NUM_THREADS: 8
          MKL_NUM_THREADS: 8
          TF_NUM_INTRAOP_THREADS: 8
          TF_NUM_INTEROP_THREADS: 1
          HF_HOME: /mnt/cache
        run: |
          python -m pytest -n 2 --dist=loadfile --make-reports=tests_tf_multi_gpu tests

      - name: Failure short reports
        if: ${{ always() }}
        run: cat reports/tests_tf_multi_gpu_failures_short.txt

      - name: Test suite reports artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_all_tests_tf_multi_gpu_test_reports
          path: reports

  send_results:
    name: Send results to webhook
    runs-on: ubuntu-latest
    if: always()
    needs: [run_tests_mindspore_gpu, run_tests_tf_gpu, run_tests_mindspore_multi_gpu, run_tests_tf_multi_gpu]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Send message to Slack
        env:
          CI_SLACK_BOT_TOKEN: ${{ secrets.CI_SLACK_BOT_TOKEN }}
          CI_SLACK_CHANNEL_ID: ${{ secrets.CI_SLACK_CHANNEL_ID }}

        run: |
          pip install slack_sdk
          python utils/notification_service.py push